version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: social-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/social-app
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:5000  # Backend serves the frontend in production
    depends_on:
      - mongo
    volumes:
      - ./server/uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  mongo-data:
