services:
  - type: web
    name: social-platform-api
    plan: free
    region: ohio
    docker:
      dockerfilePath: Dockerfile   # ✅ root-level
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: CLIENT_URL
        value: https://your-frontend-url.vercel.app
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
